# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: git clone https://github.com/cryptash/web
    - run: cd web
    - run: npm i
    - run: rm -rf src/config.ts
    - run: echo -e "const config = {server_url: \"http://localhost:9000/\",socket_url: \"ws://localhost:9000/\"}export default config" >> src/config.ts
    - run: npm run build
    - run: cp -R build/* ../build/
    - run: cd ../
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Vlad Denisov
        author_email: vlad.a.denisov@gmail.com
        message: "ci: lint & update docs"
        add: "*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

