# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: git clone https://github.com/cryptash/web
    - run: cd web && ls
    - run: cd web && npm i
    - run: cd web && rm -rf src/config.ts
    - run: cd web && ls
    - run: cp config.ts web/src
    - name: Build project
      working-directory: ./web
      run: CI=false npm run build 
    - run: mkdir build
    - run: cd web && cp -R build/* ../build/
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Vlad Denisov
        author_email: vlad.a.denisov@gmail.com
        message: "build: new build"
        add: "*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

